nextest-version = "0.9.97"

[profile.default]
fail-fast = false

[profile.ci]
fail-fast = false

[profile.ci.junit]
path = "junit.xml"

[[profile.default.overrides]]
# Run slow examples first
filter = 'test(/^example_/)'
priority = 100
